[workspace]
resolver = "3"
members = [
  "crates/*", "perf/dry"
, "perf/reduce"]

default-members = [
  "crates/*"
]

[workspace.package]
version = "0.1.0"
authors = []
edition = "2024"
license = "MIT"
repository = "https://github.com/lmeller-git/ast-testcase-reduce"

[workspace.dependencies]
ltr-core = { path = "./crates/ltr-core" }
ltr-schedule = { path = "./crates/ltr-schedule" }
rustc-hash = "2.1.2"

[profile.release]
lto = "fat"
codegen-units = 1
debug = true
