[project]
name = "lib_ramis"
version = "0.1.0"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.14"
readme = "README.md"
description = "Project 2 for course Automated Software Testing ETH"
dependencies = [
    "sqlglot>=30.8.0",
    "uvloop>=0.22.1; sys_platform != 'win32'",
]

[dependency-groups]
dev = [
  "pytest",
  "pytest-cov",
  "maturin",
]

[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "extern/ramis/bindings/python/Cargo.toml"
module-name = "lib_ramis"
features = ["extension-module"]
python-source = "extern/ramis/python"
profile = "release"

[tool.ruff]
cache-dir = ".ruff_cache"
line-length = 100

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.pyright]
include = ["python"]
extraPaths = ["python"]
venvPath = "."
venv = ".venv"
pythonVersion = "3.14"
