import asyncio


class DDMinPath:
    def to_list(self) -> list[bool]: ...


class BFScheduler:
    def __init__(self) -> None: ...
    def next(self, cancel_token: asyncio.Event) -> PyScheduledStep | None: ...
    def put_result(self, path: PyScheduledStep, event: bool) -> None: ...

class PyScheduledStep:
    def path(self) -> DDMinPath: ...

class DDMinEventInterpretor:
    def __init__(self) -> None: ...
